### ISSUE TITLE
Group doesn't always scale to content (flexbox)

### ISSUE THREAD

**Issue by Lichtjaeger** [node-red/node-red-dashboard#413]
### What are the steps to reproduce?
I have a dynamic list to show. For this, I have written the following template node:
```html
<div class="ausbeute">
  <div ng-repeat="charge in msg.payload">
    <h4>{{charge.Brennertyp}}</h4>
    <p>Gesamt: {{charge.Gesamt}}</p>
    <p>Gut: {{charge.Gute}}</p>
    <p>Prozent: {{(charge.Gute * 100 / charge.Gesamt).toFixed(1)}}%</p>
    <p>Ausfall:</p>
    <ul>
      <li ng-repeat="error in charge.fehlerListe">
        {{error.MengeFehler}} {{error.Fehler}}
      </li>
    </ul>
  </div>
</div>
```
And use this styling:
```css
<style>
  .ausbeute {
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    justify-content: space-between;
  }

  .ausbeute>div {
    flex: 1 0 24%;
  }
</style>
```
Group width is set to 24.

### What happens?
The group height is not set to the real size of the content and shows scrollbars.
![schnappschuss_071818_093800_am](https://user-images.githubusercontent.com/8598542/42924408-57fdc4dc-8b2a-11e8-9592-9768f49da62b.jpg)

In some browsers on some OS, it rescales sometimes on update. But not every time.
![schnappschuss_071918_075313_am](https://user-images.githubusercontent.com/8598542/42924506-c72ae75e-8b2a-11e8-8fdb-ecb55dadc796.jpg)

### What do you expect to happen?
The group should scale by content, even if it is in a flexbox.

### Please tell us about your environment:
The app is running on a Windows Server.

- [x] Node-RED-Dashboard version: 2.9.4
- [x] Node-RED version: 0.18.7
- [x] node.js version: 9.9.0
- [x] npm version: 5.6.0
- [x] Platform/OS: Windows 7, Windows 10, Windows Server 2016
- [x] Browser: Edge 17, Firefox 62, Chrome 67 and Brave 0.50
